# Generated by Django 3.2.4 on 2022-09-03 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Molecule',
            fields=[
                ('id_mol', models.CharField(max_length=16)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('namemol', models.CharField(db_column='nameMol', max_length=128)),
                ('referencemol', models.CharField(blank=True, db_column='referenceMol', max_length=128, null=True)),
                ('yearrefmol', models.BigIntegerField(blank=True, db_column='yearRefMol', null=True)),
                ('kingdommol', models.CharField(db_column='kingdomMol', max_length=32)),
                ('genusmol', models.CharField(blank=True, db_column='genusMol', max_length=32, null=True)),
                ('speciemol', models.CharField(blank=True, db_column='specieMol', max_length=64, null=True)),
                ('smilemol', models.TextField(db_column='smileMol')),
                ('doimol', models.CharField(blank=True, db_column='doiMol', max_length=64, null=True)),
                ('journalmol', models.CharField(blank=True, db_column='journalMol', max_length=512, null=True)),
                ('classmol', models.CharField(blank=True, db_column='classMol', max_length=128, null=True)),
                ('statemol', models.IntegerField(blank=True, db_column='stateMol', null=True)),
                ('datecreationmol', models.DateTimeField(db_column='dateCreationMol')),
                ('lastmodificationmol', models.DateTimeField(db_column='lastModificationMol')),
            ],
            options={
                'db_table': 'Molecula',
            },
        ),
        migrations.CreateModel(
            name='UserP',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=512)),
                ('password', models.CharField(max_length=64)),
                ('firstname', models.CharField(max_length=128)),
                ('lastname', models.CharField(blank=True, max_length=128, null=True)),
                ('imagecover', models.BinaryField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=512, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('username', models.CharField(max_length=128)),
                ('adress', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=512, null=True)),
                ('state', models.IntegerField(blank=True, null=True)),
                ('datecreation', models.DateTimeField()),
                ('type', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'User',
            },
        ),
    ]
