# Generated by Django 3.2.4 on 2022-09-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0002_alter_userp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='imagecover',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
