# Generated by Django 3.2.4 on 2022-09-14 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0003_alter_userp_imagecover'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
