# Generated by Django 3.2.4 on 2022-09-15 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0004_molecule_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='molecule',
            name='year',
        ),
    ]
