# Generated by Django 3.2.4 on 2022-09-15 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0005_remove_molecule_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='yearrefmol',
            field=models.PositiveSmallIntegerField(blank=True, db_column='yearRefMol', null=True),
        ),
    ]
