# Generated by Django 3.2.4 on 2022-09-15 00:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0006_alter_molecule_yearrefmol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='yearrefmol',
            field=models.PositiveSmallIntegerField(blank=True, db_column='yearRefMol', null=True, validators=[django.core.validators.MinValueValidator(1700)]),
        ),
    ]
