# Generated by Django 3.2.4 on 2022-11-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0007_alter_molecule_yearrefmol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='id_mol',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
