# Generated by Django 3.2.4 on 2022-11-30 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MolApp', '0008_alter_molecule_id_mol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userp',
            name='email',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AlterField(
            model_name='userp',
            name='state',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
